# Generated by Django 4.2.9 on 2026-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='申请人邮箱')),
                ('staff_full_name', models.CharField(default='', max_length=100, verbose_name='申请人姓名')),
                ('staff_dept', models.CharField(default='', max_length=100, verbose_name='申请人部门')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('leave_hours', models.IntegerField(verbose_name='请假时长（小时）')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('workflow_instance_id', models.IntegerField(blank=True, null=True, verbose_name='工作流实例ID')),
                ('approver_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='审批人邮箱')),
                ('approver_name', models.CharField(blank=True, max_length=100, verbose_name='审批人姓名')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
