# Generated by Django 4.2.9 on 2026-01-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='workflow_instance_id',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='process_instance_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流程实例ID'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='process_model_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='流程模型ID'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'created_at'], name='leave_api_l_status_2df3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['process_instance_id'], name='leave_api_l_process_393711_idx'),
        ),
    ]
