# Generated by Django 4.2.9 on 2026-01-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_api', '0002_remove_leaverequest_workflow_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='流程完成的时间', null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='请假的天数', max_digits=5, null=True, verbose_name='请假天数'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='请假结束日期', null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('paternity', '陪产假'), ('bereavement', '丧假')], default='annual', help_text='请假的类型', max_length=50, verbose_name='请假类型'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='请假开始日期', null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow_spec_name',
            field=models.CharField(blank=True, help_text='SpiffWorkflow 中的流程规范名称', max_length=100, null=True, verbose_name='工作流规范名称'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow_state',
            field=models.JSONField(blank=True, help_text='序列化的工作流状态，用于持久化和恢复', null=True, verbose_name='工作流状态'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_comment',
            field=models.TextField(blank=True, help_text='审批人的审批意见或备注', verbose_name='审批意见'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='审批完成的时间', null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approver_email',
            field=models.EmailField(blank=True, help_text='审批人的邮箱地址', max_length=254, null=True, verbose_name='审批人邮箱'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approver_name',
            field=models.CharField(blank=True, help_text='审批人的姓名', max_length=100, verbose_name='审批人姓名'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建的时间，自动设置', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_hours',
            field=models.IntegerField(help_text='请假的小时数，用于判断审批流程', verbose_name='请假时长（小时）'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='process_instance_id',
            field=models.CharField(blank=True, help_text='SpiffWorkflow 工作流实例的唯一标识（UUID），用于关联工作流和业务数据', max_length=100, null=True, verbose_name='流程实例ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='process_model_id',
            field=models.CharField(blank=True, help_text='BPMN 流程模型标识，格式如 "admin/admin"，对应 BPMN 文件路径', max_length=100, null=True, verbose_name='流程模型ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='详细的请假原因说明', verbose_name='请假原因'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='staff_dept',
            field=models.CharField(default='', help_text='申请人所属部门', max_length=100, verbose_name='申请人部门'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='staff_full_name',
            field=models.CharField(default='', help_text='申请人的完整姓名', max_length=100, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', help_text='当前申请的状态', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='提交审批的时间', null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新的时间，自动更新', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user_email',
            field=models.EmailField(help_text='申请人的邮箱地址，用于标识申请人', max_length=254, verbose_name='申请人邮箱'),
        ),
        migrations.CreateModel(
            name='WorkflowEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_instance_id', models.CharField(max_length=100, verbose_name='工作流实例ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='事件类型')),
                ('event_data', models.JSONField(verbose_name='事件数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '工作流事件日志',
                'verbose_name_plural': '工作流事件日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance_id'], name='leave_api_w_workflo_6fbd10_idx'), models.Index(fields=['status', 'created_at'], name='leave_api_w_status_d14828_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('description', models.TextField(verbose_name='规则描述')),
                ('priority', models.IntegerField(default=0, help_text='数字越大优先级越高', verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('leave_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='请假类型')),
                ('min_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最小时长（天）')),
                ('max_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最大时长（天）')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('min_level', models.IntegerField(blank=True, null=True, verbose_name='最小职级')),
                ('max_level', models.IntegerField(blank=True, null=True, verbose_name='最大职级')),
                ('workflow_spec_name', models.CharField(max_length=100, verbose_name='工作流规范名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批规则',
                'verbose_name_plural': '审批规则',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='leave_api_a_is_acti_36db00_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_email', models.EmailField(max_length=254, verbose_name='委托人邮箱')),
                ('proxy_email', models.EmailField(max_length=254, verbose_name='代理人邮箱')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '代理设置',
                'verbose_name_plural': '代理设置',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['principal_email', 'is_active'], name='leave_api_a_princip_3a3cc8_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_api_a_start_d_bbce58_idx')],
            },
        ),
        migrations.CreateModel(
            name='CCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_to_email', models.EmailField(max_length=254, verbose_name='抄送人邮箱')),
                ('cc_by_email', models.EmailField(max_length=254, verbose_name='抄送发起人邮箱')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='抄送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_records', to='leave_api.leaverequest', verbose_name='请假申请')),
            ],
            options={
                'verbose_name': '抄送记录',
                'verbose_name_plural': '抄送记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['leave_request'], name='leave_api_c_leave_r_127ef0_idx'), models.Index(fields=['cc_to_email', 'is_read'], name='leave_api_c_cc_to_e_c2dd87_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '批准'), ('reject', '拒绝'), ('return', '退回'), ('add_sign', '加签'), ('transfer', '转签'), ('cancel', '取消')], max_length=20, verbose_name='操作类型')),
                ('operator_email', models.EmailField(max_length=254, verbose_name='操作人邮箱')),
                ('operator_name', models.CharField(max_length=100, verbose_name='操作人姓名')),
                ('operator_role', models.CharField(max_length=50, verbose_name='操作人角色')),
                ('comment', models.TextField(blank=True, verbose_name='操作意见')),
                ('is_proxy', models.BooleanField(default=False, verbose_name='是否代理操作')),
                ('proxy_for_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='代理的原审批人邮箱')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leave_api.leaverequest', verbose_name='请假申请')),
            ],
            options={
                'verbose_name': '审批历史',
                'verbose_name_plural': '审批历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['leave_request', 'created_at'], name='leave_api_a_leave_r_dedf8a_idx')],
            },
        ),
    ]
