# Generated by Django 4.2.9 on 2026-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='接收人邮箱')),
                ('notification_type', models.CharField(choices=[('task_assigned', '任务分配'), ('task_completed', '任务完成'), ('request_approved', '申请批准'), ('request_rejected', '申请拒绝'), ('request_returned', '申请退回'), ('timeout_reminder', '超时提醒'), ('urge', '催办')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('leave_request_id', models.IntegerField(blank=True, null=True, verbose_name='关联的请假申请ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'is_read'], name='notificatio_recipie_e80745_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
