# Generated by Django 4.2.14 on 2026-03-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='品牌编码')),
                ('description', models.TextField(blank=True, verbose_name='品牌描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='品类编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='上级品类')),
            ],
            options={
                'verbose_name': '品类',
                'verbose_name_plural': '品类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('sku_name', models.CharField(max_length=200, verbose_name='SKU名称')),
                ('spu_code', models.CharField(blank=True, max_length=50, verbose_name='SPU编码')),
                ('spec_info', models.JSONField(blank=True, default=dict, help_text='如: {"颜色": "红色", "容量": "50ml"}', verbose_name='规格信息')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售'), ('out_of_stock', '缺货')], default='active', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='products.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='products.category', verbose_name='品类')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'ordering': ['-created_at'],
            },
        ),
    ]
