# Generated by Django 4.2.9 on 2026-01-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='部门的名称', max_length=100, verbose_name='部门名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='员工的唯一工号', max_length=50, unique=True, verbose_name='员工工号')),
                ('position', models.CharField(help_text='员工的职位名称', max_length=100, verbose_name='职位')),
                ('level', models.IntegerField(help_text='员工的职级，1-10，数字越大职级越高', verbose_name='职级')),
                ('email', models.EmailField(help_text='员工的邮箱地址', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(help_text='员工的联系电话', max_length=20, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(help_text='员工所属的部门', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.department', verbose_name='所属部门')),
                ('direct_manager', models.ForeignKey(blank=True, help_text='员工的直属上级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organization.employee', verbose_name='直属上级')),
                ('user', models.OneToOneField(help_text='关联的 Django 用户账号', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色的唯一名称', max_length=50, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(help_text='角色的详细描述', verbose_name='角色描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employees', models.ManyToManyField(help_text='拥有该角色的员工', related_name='roles', to='organization.employee', verbose_name='角色成员')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='该部门的负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='organization.employee', verbose_name='部门负责人'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级部门，支持树形结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.department', verbose_name='父部门'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='organizatio_employe_f754fc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='organizatio_departm_151ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['direct_manager'], name='organizatio_direct__0b04b7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='organizatio_email_0a26bb_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='organizatio_parent__d9405f_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='organizatio_name_93bf26_idx'),
        ),
    ]
