# Generated by Django 4.2.14 on 2026-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('org_unit__isnull', True), ('store__isnull', True)), fields=('user', 'role', 'scope_type'), name='unique_user_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('org_unit__isnull', False), ('store__isnull', True)), fields=('user', 'role', 'scope_type', 'org_unit'), name='unique_user_role_scope_org'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('user', 'role', 'scope_type', 'store'), name='unique_user_role_scope_store'),
        ),
    ]
