# Generated by Django 4.2.14 on 2026-03-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_month', models.CharField(help_text='格式: YYYY-MM', max_length=7, verbose_name='计划月份')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已批准'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
            ],
            options={
                'verbose_name': '销售计划',
                'verbose_name_plural': '销售计划',
                'ordering': ['-plan_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.CharField(help_text='M+1 ~ M+4', max_length=7, verbose_name='目标月份')),
                ('sales_qty', models.IntegerField(default=0, verbose_name='销售数量预测')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.salesplan', verbose_name='销售计划')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '销售计划明细',
                'verbose_name_plural': '销售计划明细',
                'ordering': ['target_month', 'sku__sku_code'],
            },
        ),
    ]
