# Generated by Django 4.2.14 on 2026-03-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_plans', to='users.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='salesplan',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_plans', to=settings.AUTH_USER_MODEL, verbose_name='提报人'),
        ),
        migrations.AlterUniqueTogether(
            name='salesplanitem',
            unique_together={('plan', 'sku', 'target_month')},
        ),
        migrations.AlterUniqueTogether(
            name='salesplan',
            unique_together={('plan_month', 'submitter')},
        ),
    ]
