# Generated by Django 4.2.14 on 2026-03-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_orgunit_store_user_org_unit_storemembership'),
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='任务标题')),
                ('plan_month', models.CharField(help_text='格式: YYYY-MM', max_length=7, verbose_name='计划月份')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('closed', '已关闭'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_campaigns', to='users.orgunit', verbose_name='范围组织')),
            ],
            options={
                'verbose_name': '计划批次',
                'verbose_name_plural': '计划批次',
                'ordering': ['-plan_month', '-created_at'],
                'unique_together': {('plan_month', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '待填写'), ('submitted', '待审核'), ('approved', '已通过'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='任务备注')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='填写负责人')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.plancampaign', verbose_name='计划批次')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tasks', to='users.orgunit', verbose_name='组织归属')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_tasks', to='users.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'ordering': ['-campaign__plan_month', 'store__code'],
                'unique_together': {('campaign', 'store')},
            },
        ),
        migrations.CreateModel(
            name='PlanTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.CharField(help_text='M+1 ~ M+4', max_length=7, verbose_name='目标月份')),
                ('sales_qty', models.IntegerField(default=0, verbose_name='销售数量预测')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.plantask', verbose_name='计划任务')),
            ],
            options={
                'verbose_name': '任务计划明细',
                'verbose_name_plural': '任务计划明细',
                'ordering': ['target_month', 'sku__sku_code'],
                'unique_together': {('task', 'sku', 'target_month')},
            },
        ),
    ]
