# Generated by Django 4.2.29 on 2026-03-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesplan',
            options={'ordering': ['-plan_month', '-created_at'], 'verbose_name': '个人销售计划', 'verbose_name_plural': '个人销售计划'},
        ),
        migrations.AlterModelOptions(
            name='salesplanitem',
            options={'ordering': ['target_month', 'sku__sku_code'], 'verbose_name': '个人销售计划明细', 'verbose_name_plural': '个人销售计划明细'},
        ),
        migrations.RemoveIndex(
            model_name='plancampaign',
            name='campaign_month_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantask',
            name='task_campaign_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantask',
            name='task_assignee_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantask',
            name='task_store_campaign_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantaskitem',
            name='taskitem_task_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantaskitem',
            name='taskitem_sku_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesplan',
            name='salesplan_month_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesplan',
            name='salesplan_submitter_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesplan',
            name='salesplan_status_submitted_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesplanitem',
            name='planitem_plan_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesplanitem',
            name='planitem_sku_month_idx',
        ),
        migrations.AddField(
            model_name='plancampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='填报结束日期'),
        ),
        migrations.AddField(
            model_name='plancampaign',
            name='plan_type',
            field=models.CharField(choices=[('monthly', '月度计划'), ('ad_hoc', '临时销售计划'), ('new_product', '新品计划')], default='monthly', max_length=30, verbose_name='计划类型'),
        ),
        migrations.AddField(
            model_name='plancampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='填报开始日期'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='approval_status',
            field=models.CharField(choices=[('not_started', '未开始'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='not_started', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='current_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='当前审批步骤'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='editable_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='可编辑截止时间'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='last_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近提交时间'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='last_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近撤回时间'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='pending_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='当前待审批人'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='round_no',
            field=models.PositiveIntegerField(default=0, verbose_name='审批轮次'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='最近提交人'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '开启中'), ('closed', '已结束'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批完成时间'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='填报负责人'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='status',
            field=models.CharField(choices=[('draft', '待填报'), ('submitted', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='draft', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次提交时间'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='sales_qty',
            field=models.IntegerField(default=0, verbose_name='销售预测数量'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='sales_qty',
            field=models.IntegerField(default=0, verbose_name='销售预测数量'),
        ),
    ]
