# Generated by Django 4.2.14 on 2026-03-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0005_alter_salesplan_options_alter_salesplanitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancampaign',
            options={'ordering': ['-plan_month', '-created_at'], 'verbose_name': 'Plan Campaign', 'verbose_name_plural': 'Plan Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='plantask',
            options={'ordering': ['-campaign__plan_month', 'store__code'], 'verbose_name': 'Plan Task', 'verbose_name_plural': 'Plan Tasks'},
        ),
        migrations.AlterModelOptions(
            name='plantaskitem',
            options={'ordering': ['target_month', 'sku__sku_code'], 'verbose_name': 'Plan Task Item', 'verbose_name_plural': 'Plan Task Items'},
        ),
        migrations.AlterModelOptions(
            name='salesplan',
            options={'ordering': ['-plan_month', '-created_at'], 'verbose_name': 'Sales Plan', 'verbose_name_plural': 'Sales Plans'},
        ),
        migrations.AlterModelOptions(
            name='salesplanitem',
            options={'ordering': ['target_month', 'sku__sku_code'], 'verbose_name': 'Sales Plan Item', 'verbose_name_plural': 'Sales Plan Items'},
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_campaigns', to='users.orgunit', verbose_name='Org Unit'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='plan_month',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7, verbose_name='Plan Month'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('ad_hoc', 'Ad Hoc'), ('new_product', 'New Product')], default='monthly', max_length=30, verbose_name='Plan Type'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plancampaign',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='approval_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='not_started', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.plancampaign', verbose_name='Plan Campaign'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='current_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Step'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='editable_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editable Until'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='last_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Submitted At'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='last_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Withdrawn At'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tasks', to='users.orgunit', verbose_name='Org Unit'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='pending_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Pending Approver'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='round_no',
            field=models.PositiveIntegerField(default=0, verbose_name='Round No'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_tasks', to='users.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_plan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='sales_qty',
            field=models.IntegerField(default=0, verbose_name='Sales Qty'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Stock Qty'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='target_month',
            field=models.CharField(help_text='M+1 ~ M+4', max_length=7, verbose_name='Target Month'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.plantask', verbose_name='Plan Task'),
        ),
        migrations.AlterField(
            model_name='plantaskitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_plans', to='users.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='plan_month',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7, verbose_name='Plan Month'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_plans', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.salesplan', verbose_name='Sales Plan'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='sales_qty',
            field=models.IntegerField(default=0, verbose_name='Sales Qty'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Stock Qty'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='target_month',
            field=models.CharField(help_text='M+1 ~ M+4', max_length=7, verbose_name='Target Month'),
        ),
        migrations.AlterField(
            model_name='salesplanitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
