# Generated by Django 4.2.14 on 2026-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('flow_type', models.CharField(choices=[('sales_plan', '销售计划审批')], max_length=50, verbose_name='流程类型')),
                ('levels', models.JSONField(default=list, help_text='如: [{"level": 1, "role": "supervisor"}, {"level": 2, "role": "manager"}]', verbose_name='审批层级配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
                'ordering': ['flow_type', 'department'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(verbose_name='审批层级')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '退回')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
