# Generated by Django 4.2.14 on 2026-03-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='plans.salesplan', verbose_name='销售计划'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='department',
            field=models.ForeignKey(blank=True, help_text='为空表示全局默认流程', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='适用部门'),
        ),
    ]
