# Generated by Django 4.2.14 on 2026-03-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plancampaign_plantask_plantaskitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(verbose_name='审批层级')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '退回')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='plans.plantask', verbose_name='计划任务')),
            ],
            options={
                'verbose_name': '任务审批记录',
                'verbose_name_plural': '任务审批记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
