# Generated by Django 4.2.29 on 2026-03-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0005_alter_salesplan_options_alter_salesplanitem_options_and_more'),
        ('users', '0003_add_performance_indexes'),
        ('approvals', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1, verbose_name='审批轮次')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='实例状态')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='当前步骤')),
                ('submit_comment', models.TextField(blank=True, verbose_name='提交说明')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务审批实例',
                'verbose_name_plural': '任务审批实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='approvalflow',
            options={'ordering': ['flow_type', 'scope_type', 'name'], 'verbose_name': '审批流程', 'verbose_name_plural': '审批流程'},
        ),
        migrations.RemoveIndex(
            model_name='approvalflow',
            name='approvalflow_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalrecord',
            name='approval_plan_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalrecord',
            name='approval_approver_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskapprovalrecord',
            name='taskapproval_task_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskapprovalrecord',
            name='taskapproval_approver_time_idx',
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='users.orgunit', verbose_name='适用组织'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='scope_type',
            field=models.CharField(choices=[('global', '全局'), ('department', '部门'), ('org_unit', '组织'), ('store', '店铺')], default='global', max_length=20, verbose_name='适用范围类型'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='users.store', verbose_name='适用店铺'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='department',
            field=models.ForeignKey(blank=True, help_text='为空表示不按部门限制', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='适用部门'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='flow_type',
            field=models.CharField(choices=[('sales_plan', '销售计划审批'), ('plan_task', '任务审批')], max_length=50, verbose_name='流程类型'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='levels',
            field=models.JSONField(default=list, help_text='例如: [{"step": 1, "approver_type": "manager"}]', verbose_name='审批层级配置'),
        ),
        migrations.AlterField(
            model_name='taskapprovalrecord',
            name='action',
            field=models.CharField(choices=[('approve', '通过'), ('reject_to_previous', '驳回上一步'), ('reject_to_submitter', '驳回提交人'), ('withdraw', '撤回'), ('resubmit', '重新提交')], max_length=30, verbose_name='审批动作'),
        ),
        migrations.AddField(
            model_name='taskapprovalinstance',
            name='pending_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approval_instances', to=settings.AUTH_USER_MODEL, verbose_name='待审批人'),
        ),
        migrations.AddField(
            model_name='taskapprovalinstance',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approval_instances', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='taskapprovalinstance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='plans.plantask', verbose_name='计划任务'),
        ),
        migrations.AddField(
            model_name='taskapprovalrecord',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='approvals.taskapprovalinstance', verbose_name='审批实例'),
        ),
        migrations.AlterUniqueTogether(
            name='taskapprovalinstance',
            unique_together={('task', 'round_no')},
        ),
    ]
