# Generated by Django 4.2.14 on 2026-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_taskapprovalinstance_alter_approvalflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapprovalinstance',
            name='steps_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='提交时冻结的审批链快照，避免后续组织架构变更影响进行中的审批', verbose_name='审批步骤快照'),
        ),
    ]
