DEFAULT_PERMISSION_CONFIGS = [
    {'code': 'dashboard.view', 'module': 'dashboard', 'resource': 'dashboard', 'action': 'view', 'description': 'View dashboard'},
    {'code': 'products.sku.view', 'module': 'products', 'resource': 'sku', 'action': 'view', 'description': 'View SKU catalog'},
    {'code': 'plans.task.view', 'module': 'plans', 'resource': 'task', 'action': 'view', 'description': 'View planning tasks'},
    {'code': 'plans.task.manage', 'module': 'plans', 'resource': 'task', 'action': 'manage', 'description': 'Create and manage planning campaigns and tasks'},
    {'code': 'plans.task.edit', 'module': 'plans', 'resource': 'task', 'action': 'edit', 'description': 'Edit planning task contents'},
    {'code': 'plans.task.submit', 'module': 'plans', 'resource': 'task', 'action': 'submit', 'description': 'Submit planning tasks'},
    {'code': 'plans.task.withdraw', 'module': 'plans', 'resource': 'task', 'action': 'withdraw', 'description': 'Withdraw planning tasks'},
    {'code': 'plans.task.export', 'module': 'plans', 'resource': 'task', 'action': 'export', 'description': 'Export planning tasks'},
    {'code': 'plans.report.view', 'module': 'plans', 'resource': 'report', 'action': 'view', 'description': 'View planning reports'},
    {'code': 'approvals.center.view', 'module': 'approvals', 'resource': 'center', 'action': 'view', 'description': 'View approval center'},
    {'code': 'approvals.instance.view', 'module': 'approvals', 'resource': 'instance', 'action': 'view', 'description': 'View approval instances'},
    {'code': 'approvals.instance.approve', 'module': 'approvals', 'resource': 'instance', 'action': 'approve', 'description': 'Approve or reject approval instances'},
    {'code': 'permissions.center.view', 'module': 'permissions', 'resource': 'center', 'action': 'view', 'description': 'View permission center'},
    {'code': 'mechanisms.center.view', 'module': 'mechanisms', 'resource': 'center', 'action': 'view', 'description': 'View mechanism center'},
    {'code': 'analytics.center.view', 'module': 'analytics', 'resource': 'center', 'action': 'view', 'description': 'View analytics center'},
    {'code': 'integrations.center.view', 'module': 'integrations', 'resource': 'center', 'action': 'view', 'description': 'View integrations center'},
]

DEFAULT_ROLE_CONFIGS = [
    {'code': 'admin', 'name': 'Administrator', 'role_type': 'system', 'priority': 10, 'is_system': True},
    {'code': 'manager', 'name': 'Manager', 'role_type': 'system', 'priority': 20, 'is_system': True},
    {'code': 'supervisor', 'name': 'Supervisor', 'role_type': 'system', 'priority': 30, 'is_system': True},
    {'code': 'staff', 'name': 'Staff', 'role_type': 'system', 'priority': 40, 'is_system': True},
]

DEFAULT_ROLE_PERMISSION_MAP = {
    'admin': [
        'dashboard.view', 'products.sku.view', 'plans.task.view', 'plans.task.manage', 'plans.task.edit',
        'plans.task.submit', 'plans.task.withdraw', 'plans.task.export', 'plans.report.view',
        'approvals.center.view', 'approvals.instance.view', 'approvals.instance.approve',
        'permissions.center.view', 'mechanisms.center.view', 'analytics.center.view', 'integrations.center.view',
    ],
    'manager': [
        'dashboard.view', 'products.sku.view', 'plans.task.view', 'plans.task.manage', 'plans.task.edit',
        'plans.task.submit', 'plans.task.withdraw', 'plans.task.export', 'plans.report.view',
        'approvals.center.view', 'approvals.instance.view', 'approvals.instance.approve',
        'mechanisms.center.view', 'analytics.center.view',
    ],
    'supervisor': [
        'dashboard.view', 'products.sku.view', 'plans.task.view', 'plans.task.manage', 'plans.task.edit',
        'plans.task.submit', 'plans.task.withdraw', 'plans.task.export', 'plans.report.view',
        'approvals.center.view', 'approvals.instance.view', 'approvals.instance.approve',
        'mechanisms.center.view', 'analytics.center.view',
    ],
    'staff': [
        'dashboard.view', 'products.sku.view', 'plans.task.view', 'plans.task.edit', 'plans.task.submit',
        'plans.task.withdraw', 'approvals.center.view', 'approvals.instance.view',
    ],
}

DEFAULT_PAGE_CONFIGS = [
    {
        'page_key': 'dashboard',
        'label': '首页',
        'url_name': 'dashboard',
        'permission_code': 'dashboard.view',
        'show_in_menu': True,
        'menu_order': 10,
        'allow_all_users': True,
        'allowed_roles': [],
    },
    {
        'page_key': 'products',
        'label': 'SKU管理',
        'url_name': 'products:sku_list',
        'permission_code': 'products.sku.view',
        'show_in_menu': True,
        'menu_order': 20,
        'allow_all_users': True,
        'allowed_roles': [],
    },
    {
        'page_key': 'plans',
        'label': '任务列表',
        'url_name': 'plans:my_tasks',
        'permission_code': 'plans.task.view',
        'show_in_menu': True,
        'menu_order': 30,
        'allow_all_users': True,
        'allowed_roles': [],
    },
    {
        'page_key': 'campaigns',
        'label': '计划批次',
        'url_name': 'plans:campaign_create',
        'permission_code': 'plans.task.manage',
        'show_in_menu': True,
        'menu_order': 40,
        'allow_all_users': False,
        'allowed_roles': ['admin', 'manager', 'supervisor'],
    },
    {
        'page_key': 'approvals',
        'label': '审批中心',
        'url_name': 'approvals:center',
        'permission_code': 'approvals.center.view',
        'show_in_menu': True,
        'menu_order': 50,
        'allow_all_users': True,
        'allowed_roles': [],
    },
    {
        'page_key': 'reports',
        'label': '报表分析',
        'url_name': 'plans:plan_report',
        'permission_code': 'plans.report.view',
        'show_in_menu': True,
        'menu_order': 60,
        'allow_all_users': False,
        'allowed_roles': ['admin', 'manager', 'supervisor'],
    },
    {
        'page_key': 'permissions',
        'label': '权限中心',
        'url_name': 'permissions:center',
        'permission_code': 'permissions.center.view',
        'show_in_menu': True,
        'menu_order': 70,
        'allow_all_users': False,
        'allowed_roles': ['admin'],
    },
    {
        'page_key': 'mechanisms',
        'label': '机制配置',
        'url_name': 'mechanisms:center',
        'permission_code': 'mechanisms.center.view',
        'show_in_menu': True,
        'menu_order': 80,
        'allow_all_users': False,
        'allowed_roles': ['admin', 'manager', 'supervisor'],
    },
    {
        'page_key': 'analytics',
        'label': '数据分析',
        'url_name': 'analytics:center',
        'permission_code': 'analytics.center.view',
        'show_in_menu': True,
        'menu_order': 90,
        'allow_all_users': False,
        'allowed_roles': ['admin', 'manager', 'supervisor'],
    },
    {
        'page_key': 'integrations',
        'label': '系统集成',
        'url_name': 'integrations:center',
        'permission_code': 'integrations.center.view',
        'show_in_menu': True,
        'menu_order': 100,
        'allow_all_users': False,
        'allowed_roles': ['admin'],
    },
]

